version: "3"

services:

  redis:
    image: "redis:alpine"
    restart: "unless-stopped"
    ports:
      - "6379:6379"

  api:
    build:
      context: mini-event-api/
      dockerfile: Dockerfile 
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - "redis"

  ui:
    build:
      context: mini-event-ui/
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "9090:9090"
    depends_on:
      - "api"
